### ISSUE TITLE
Upload profile picture and enable gravatar

### ISSUE THREAD

**Issue by TheoWolf** [databrary/databrary.org#49]
**TODO:**
* Backend: 
    - [x] Add DB column for users avatar or profile picture
    - [ ] Add logic in sign-upload to see if picture exists in DB
    - [x] MinIO bucket for pictures 
    - [ ] Resize pictures for different usage (for the thumbnail)
* Frontend:
   - [x] Hook the gravatar logic
   - [ ] Add uppy upload to the profile settings
   - [x] Fetch gravatar | avatar in the notification menu
